CREATE PROC [dbo].[sp_timkho]
@makho NCHAR(4)
AS
BEGIN
	IF EXISTS (SELECT MAKHO FROM dbo.Kho WHERE MAKHO = @makho)
		SELECT * FROM dbo.Kho WHERE MAKHO = @makho
	ELSE
		IF EXISTS (SELECT MAKHO FROM LINK1.QLVT_DATHANG.dbo.Kho WHERE MAKHO = @makho)
			SELECT * FROM LINK1.QLVT_DATHANG.dbo.Kho WHERE MAKHO = @makho
		ELSE
			RAISERROR(N'Kho bạn tìm không tồn tại',16,1)
END